### ISSUE TITLE
(feat) Load table data into frontend.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/redbird-clone#4]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 2h | 2h10m | 2h | 0h |

**acceptance criteria:**
- the frontend has a table that uses data from backend
- data is loaded into the table when the html endpoint is shown
- table columns contain different fields from the data entries

**task breakdown:**
- [x] `backend/model`, rename messages and endpoint messages to `Document`, update endpoints in other file [30m]
- [x] `testing/api/backend`, update test fixtures [10m]
- [x] `frontend/client`, add http client for backend data [30m]
- [x] `frontend/api/content`, fetch backend data and pass to `TableHeaderRow` and `TableRow`, maybe refactor [30m]
- [x] create, review, merge pull request; developer and testing instructions [30m]

**technical details:**
- we can populate database with demo data fixture using the endpoint tests in `testing/api/backend/`
- in `frontend` service we should create `client.ts` that fetches `backend` service JSON endpoints
- `Document` model contains `created` and `lastModified` which should be used for columns
- besides `authorId` we should also have an `authorName`
- JSON endpoint just uses `kv.list()` sorted by key-path. for advanced filters we'll need a full-text store in the future.

**out of scope:**
- endpoint tests for the html response using server-side DOM (e.g. linkedom which uses triple-linked lists)

**Comment by hastebrot** [comment]
closed by #7 and #8.
