### ISSUE TITLE
(feat) Table group and filter popovers.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/redbird-clone#5]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 4h | 5h | 2h | 3h |

definition apple developer:
> A popover is a transient view that appears above other content when people click or tap a control or interactive area.

definition ibm carbon design:
> A popover is a layer that appears above all other content on the page. Only one popover can appear at a time and can contain varying text and interactive elements. Popovers are used as a base layer in some of our components like tooltips, overflow menus, and dropdown menus.

**acceptance criteria:**
- we have an action-bar with group and filter button
- group and filter button show a popover on click
- popover can be closed by clicking outside of popover
- popover content allow to make a selection
- current selection is shown as label in group and filter button

**task breakdown:**
- [x] `frontend/api/content`, add `Dropdown` component based on `<dialog>` and `<button>`. add `htmx.showModal()` and `htmx.closeModal()` to `index.html` [2h]
-  [ ] `frontend/api/content`, add "group" button into custom popover and use radios and submit button as popover content [1h]
-  [ ] `frontend/api/content`, add "filter" button into custom popover and use checkboxes and submit button as popover content [1h]
-  [ ] show current selection in "group" and "filter" button [30m]
-  [ ] create, review, merge pull request; developer and testing instructions [30m]

**technical details:**
- we can use `<dialog>` as a container for the popover content and to trigger the popup open. using `hx-trigger` we can call `showModal()` which displays the dialog in top-layer along `::backdrop` pseudo-element, https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal
- clicks inside and outside the dialog element are consumed as events
- we need to position the dialog using coordinates `getBoundingRect()` of its parent. when the dialog is within a scrollable view it prevents scrolling when the dialog is shown. we have to replace the default `position: fixed` of the dialog with `position: absolute` (it will be positioned relative to the document since it's displayed in the top-layer). when the viewport is resized we'll not reposition the popup.
- popover content for selection could be just input checkboxes or radio buttons. within a `<form>` we can send them to the backend.
