### ISSUE TITLE
(feat) Filter table data by all and unread.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/redbird-clone#6]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 4h |  |  |  |

**acceptance criteria:**
- we have a toggle button for "all" and "unread" filter states
- the toggle button shows the count of items for these states, e.g. "all (10)" and "unread (2)"
- table rows are filtered depending on the selected toggle button state
- we indicate which table rows are unread using a blue circle (out of scope: no update on click or table row selection of the `is-read` status needed)

**task breakdown:**
- [ ] `backend/model`, add enum `ReadStatus`, there are three states `unknown`, `read`, `not-read`
- [ ] `backend/model`, add endpoint messages to fetch the read status using document id, update `client`, update `api`.
- [ ] `frontend/api/content`, add toggle button, fetch number of "all" and "unread" documents. when we fetch documents, then set "all" to number of documents in table, and "unread" to zero. then fetch read-status per document and update "unread" status when all document status were resolved
- [ ] `frontend/api/content`, update table, add additional `hx-get` for read-status, indicate read status using blue circle and table row gradient
- [ ] create, review, merge pull request; developer and testing instructions [30m]

**open questions:**
- Q: should we fetch read-status per table-view, or per table-row? per table-view would make updates to the count of documents easier. what happens when we fetch additional rows then we need to calculate the sum of number of documents. should we really show the read-status per loaded documents in table or for all documents?
  - A: keep the kv-store and later migrate to ft-store. for number of "all" documents and "unread" documents fetch `["documents", document.id]` prefix key and `["documents-by-user", user.id, "read-status", document.id]` prefix key. for context: we use additional keys for aggregation of values according to our use-cases in frontend.

**technical details:**
- toggle button uses typical stripe design. each state just has a `hx-trigger="click"` handler
- needs an endpoint that returns `is-read` status per-user. just use fake data.
- table cells can show a blue circle to indicate unread. we can use `hx-trigger="load"` handler to make additional request per table-row for the `is-read` status
- the html endpoint needs to know which `is-read` status it needs to filter
- there are database entries that contain `is-read` status per entry `id`. a lookup per entry is required.

**out of scope:**
- update the read status when the table row was clicked, e.g. the details for the table row were shown
- first table cell with gradient for unread table rows
